{
    "album": {
        "album_type": "single",
        "artists": [{
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX"
                },
                "href": "https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX",
                "id": "1TA5sGRlKUJXBN4ZyJuDIX",
                "name": "Blessd",
                "type": "artist",
                "uri": "spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX"
            },
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/3HH6yOn1yJNZo3RY5zEfy5"
                },
                "href": "https://api.spotify.com/v1/artists/3HH6yOn1yJNZo3RY5zEfy5",
                "id": "3HH6yOn1yJNZo3RY5zEfy5",
                "name": "Javiielo",
                "type": "artist",
                "uri": "spotify:artist:3HH6yOn1yJNZo3RY5zEfy5"
            },
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/5wUO3A6DT4tO5UDz21kE2Y"
                },
                "href": "https://api.spotify.com/v1/artists/5wUO3A6DT4tO5UDz21kE2Y",
                "id": "5wUO3A6DT4tO5UDz21kE2Y",
                "name": "Neutro Shorty",
                "type": "artist",
                "uri": "spotify:artist:5wUO3A6DT4tO5UDz21kE2Y"
            }
        ],
        "available_markets": [
            "AD",
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/6J5v3KTP6mYNd02doPo4mM"
        },
        "href": "https://api.spotify.com/v1/albums/6J5v3KTP6mYNd02doPo4mM",
        "id": "6J5v3KTP6mYNd02doPo4mM",
        "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b273b8d8868e623782ce1bc05808",
                "width": 640
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e02b8d8868e623782ce1bc05808",
                "width": 300
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d00004851b8d8868e623782ce1bc05808",
                "width": 64
            }
        ],
        "name": "Dos Problemas (feat. Big Soto) [Remix]",
        "release_date": "2021-08-06",
        "release_date_precision": "day",
        "total_tracks": 1,
        "type": "album",
        "uri": "spotify:album:6J5v3KTP6mYNd02doPo4mM"
    },
    "artists": [{
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/1TA5sGRlKUJXBN4ZyJuDIX"
            },
            "href": "https://api.spotify.com/v1/artists/1TA5sGRlKUJXBN4ZyJuDIX",
            "id": "1TA5sGRlKUJXBN4ZyJuDIX",
            "name": "Blessd",
            "type": "artist",
            "uri": "spotify:artist:1TA5sGRlKUJXBN4ZyJuDIX"
        },
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/3HH6yOn1yJNZo3RY5zEfy5"
            },
            "href": "https://api.spotify.com/v1/artists/3HH6yOn1yJNZo3RY5zEfy5",
            "id": "3HH6yOn1yJNZo3RY5zEfy5",
            "name": "Javiielo",
            "type": "artist",
            "uri": "spotify:artist:3HH6yOn1yJNZo3RY5zEfy5"
        },
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/5wUO3A6DT4tO5UDz21kE2Y"
            },
            "href": "https://api.spotify.com/v1/artists/5wUO3A6DT4tO5UDz21kE2Y",
            "id": "5wUO3A6DT4tO5UDz21kE2Y",
            "name": "Neutro Shorty",
            "type": "artist",
            "uri": "spotify:artist:5wUO3A6DT4tO5UDz21kE2Y"
        },
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/2TQ4CGgxxCWHqa9yYIGDoU"
            },
            "href": "https://api.spotify.com/v1/artists/2TQ4CGgxxCWHqa9yYIGDoU",
            "id": "2TQ4CGgxxCWHqa9yYIGDoU",
            "name": "Big Soto",
            "type": "artist",
            "uri": "spotify:artist:2TQ4CGgxxCWHqa9yYIGDoU"
        }
    ],
    "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
    ],
    "disc_number": 1,
    "duration_ms": 243216,
    "explicit": true,
    "external_ids": {
        "isrc": "COA6W2101724"
    },
    "external_urls": {
        "spotify": "https://open.spotify.com/track/7bx66Je824Iak8c1CfsMrE"
    },
    "href": "https://api.spotify.com/v1/tracks/7bx66Je824Iak8c1CfsMrE",
    "id": "7bx66Je824Iak8c1CfsMrE",
    "is_local": false,
    "name": "Dos Problemas (feat. Big Soto) - Remix",
    "popularity": 76,
    "preview_url": "https://p.scdn.co/mp3-preview/b6a10697a74943483fb8180e790a101dba13fab6?cid=d70d86f359464fa7813434cedffcc29e",
    "track_number": 1,
    "type": "track",
    "uri": "spotify:track:7bx66Je824Iak8c1CfsMrE"
}